language: node_js
node_js: 8

before_script:
    - npm install firebase-tools -g
    - npm install
    - cd functions && npm install
    - npm run build

script:
    - firebase deploy --token "1/YhcJtmRPrjaIzHCQMDEButByWPMujLNRv4ldN_kQnas"

branch:
    only:
        -master
