language: node_js
node_js: 8

before_script:
  - npm install firebase-tools -g
  - npm install
  - cd functions && npm install
  - cd ..

stages:
  - name: compile
    if: branch != Firebase-build
  - name: deploy
    if: branch = Firebase-build

jobs:
  include:
    - stage: compile
      script: npm run build
    - stage: deploy
      script:
        - npm run build
        - firebase deploy --token "1/YhcJtmRPrjaIzHCQMDEButByWPMujLNRv4ldN_kQnas"
